title: Harleen Kaur Hora # your name (or website title) here
logo: "/images/Harleen_Kaur-2-circleedit1.png?raw=true" # your photo (or logo) here
#https://www.gimp.org/tutorials/CircleImage/
description: > # your text below (remove <br> elements if you don't need line breaks)   #Experienced at feature space generation, utilizing classification and regression models, using predictive data modeling to deliver insights and implement solutions to complex scientific problems.  
  <br><br>
  Data Analyst/BI Developer, with 3+ years of experience  in data handling, which includes manipulation, cleaning, reporting, and automation. I utilize Python alongside visualization tools like PowerBI, Tableau, and Kibana for enhanced data analysis. Proficient in Databricks, SQL, Python, Pandas, NumPy, and Matplotlib, I've successfully converted complex datasets into actionable insights. Furthermore, I've delved into cloud technology, working with AWS and GCP to improve data analytics and storage, making processes more efficient and scalable. I also have a history of identifying vital KPIs for impactful data-driven decisions.
  <br><br>
  
  <a href="https://www.linkedin.com/in/harleen-kaur-hora/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
